/* font.h - Built-in bitmap font
 *
 * A fixed-cell 1bpp font compiled into the kernel, so text rendering never
 * depends on a file being present on a disk that may not be mounted yet.
 * The glyph data is generated by tools/genfont.py into font_data.c.
 */
#ifndef KERNEL_FONT_H
#define KERNEL_FONT_H

#include <kernel/types.h>

extern const u8  font_cell_w;
extern const u8  font_cell_h;
extern const u16 font_first_char;
extern const u16 font_glyph_count;

/* Codepoint -> glyph index, or -1 when the kernel has no glyph for it. */
extern const s16 font_index[256];

/* One byte per row, bit 0 is the leftmost pixel. */
const u8* font_glyph_rows(u16 index);

/* Convenience: glyph index for a codepoint, or -1. */
static inline s16 font_glyph_index(unsigned char c) {
    return font_index[c];
}

#endif
